name: GPT Cli Upload Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: false

jobs:
  upload-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: uploading package
        run: make upload
        env:
          VERSION: ${{ inputs.version }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
