name: GPT Cli Upload Package
on:
  workflow_dispatch:

jobs:
  upload-package:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: uploading package
      run: make upload
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
