name: Upload Package
on:
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  upload-package:
    runs-on: ubuntu-latest
    python-version: '3.11'
    steps:
      - uses: actions/checkout@v3
      - name: uploading package
        run: make upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
